apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-bank-api-deployment
  labels:
    app: simple-bank-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-bank-api
  template:
    metadata:
      labels:
        app: simple-bank-api

    spec:
      containers:
        - name: simple-bank-api
          image: 730335250704.dkr.ecr.ap-southeast-1.amazonaws.com/simplebank:419f1b753afb95d34748389004eedf1ef4bd87bf
          ports:
            - containerPort: 8080
